target_machine:
  - armv7l
centos_machine:
  - armv7hl
cross_target_platform:
  - linux-armv7l
sysroot_cdt_arch:
  - armv7l

ctng_vendor:
  - conda
sysroot_cdt_name:
  - cos7

zip_keys:
  - - target_machine
    - cross_target_platform
    - centos_machine
    - sysroot_cdt_arch
